### ISSUE TITLE
VerletList Container

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#10]
Implement the VerletListContainer
* should reuse functionality from LinkedCells

deletion of particles should set VerletLists::_neighborListIsValid to false
benchmark for rebuild + md or so -- how much speedup is theoretically possible
add real life example and functionality needed
updating halo particles without change of data structure - i.e. get particle by id or position and modify it that way
particle iterators: should they include the halo particles?

Todos from #25 
ToDo:
1. deletion of particles should set VerletLists::_neighborListIsValid to false
2. <del> benchmark for rebuild + md or so -- how much speedup is theoretically possible</del>
3. <del>add real life example and functionality needed</del>
   * <del>updating halo particles without change of data structure - i.e. get particle by id or position and modify it that way</del>
   * <del>particle iterators: should they include the halo particles?</del>
4. Vectorization (new issue #35)

**Comment by SteffenSeckler** [comment]
@AutoPas/design 
any ideas for proper implementations of the SoALoader and SoAExtractor functions?
currently they are cell based. Do probably have to change that...

**Comment by SteffenSeckler** [comment]
see also https://github.com/orgs/AutoPas/teams/design/discussions/6

**Comment by SteffenSeckler** [comment]
Todo
2. benchmark for rebuild + md or so -- how much speedup is theoretically possible
is done (see https://github.com/AutoPas/AutoPas/commit/56911aea93cd016c59be713159a6056beef52500 and https://github.com/AutoPas/AutoPas/commit/c884235435a468687010117f51695296b25e04a7)

**Comment by tchipev** [comment]
very cool :)
how does it look like with vectorization? This paper discusses simple LJ Verlet list implementation with intrinsics, maybe you can look at it:
https://software.intel.com/sites/default/files/article/478279/mxhmd.final.pdf

Also, in LAMMPS, the Verlet lists are vectorized with compiler pragmas only (I think) and the code is more or less readable. You can look at it in void PairLJCutIntel::eval(...) here:
https://github.com/lammps/lammps/blob/master/src/USER-INTEL/pair_lj_cut_intel.cpp

Best,
Nikola

**Comment by SteffenSeckler** [comment]
see https://github.com/AutoPas/AutoPas/wiki/Benchmarks

**Comment by SteffenSeckler** [comment]
@FG-TUM @tchipev 
currently thinking about how to make an interface to exchange particles for verlet lists.
even if the verlet list is reused, we still need to update the halo particles.
I have implemented a method to update haloparticles, that works by finding the particle in the cell it is currently inside of (or one of the neighboring cells).
this works well, however you need to feed it with particles that are already added to the container.

therefore a requirement is that ALWAYS the exact same particles are copied for the halo particles. This is not new and @tchipev mentioned this already a couple of times.

we have multiple different ways to do this:
* let the user handle it: he saves a list of pointers to the particles he first copied
* autopas helps: we introduce sth. like a FixedHaloCellIterator. This iterator always iterates over the same halo cells the cells are defined using some bounding box.

Opinions?

**Comment by SteffenSeckler** [comment]
real live example is completed in #34.
**note**: in the example (examples/sph-verlet) the skin to cutoff ratio should not to be bigger than 0.04. Otherwise too few cells are existing and the performance drops to that below of linked-cells (good example for auto-tuning!)
