### ISSUE TITLE
Update archer

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#117]
**Is your feature request related to a problem? Please describe.**
Archer currently used in Jenkins is based on clang version 4.0.0. This clang version has a bug of [overreporting "missing braces"](https://bugs.llvm.org/show_bug.cgi?id=21629)

**Describe the solution you'd like**
Update to archer 2 (based on clang 6)

**Describe alternatives you've considered**
Ignore -Wmissing-braces -> meh

**Comment by SteffenSeckler** [comment]
once this is done
remove filtering of -Wmissing-braces

**Comment by SteffenSeckler** [comment]
I have archer-v2.0.0 running, however, I get a lot of warnings.
As the previous version of archer (v1.0.0) with clang 4.0 was running fine, I suppose that archer is the problem.

**Comment by SteffenSeckler** [comment]
fixed using
export TSAN_OPTIONS="ignore_noninstrumented_modules=1"
see https://github.com/PRUNERS/archer/issues/87

**Comment by SteffenSeckler** [comment]
updated archer to v2.0.0 -> closed
