### ISSUE TITLE
md-flex allow selection of newton3

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#144]
**Is your feature request related to a problem? Please describe.**
Currently md-flex is not able to benchmark non-newton3 runs.
Especially needed to compare different things of new verlet-list implementations.

**Describe the solution you'd like**
Make it able to benchmark non-newton3 runs.

**Describe alternatives you've considered**
Benchmark / Check with sph examples

**Comment by FG-TUM** [comment]
this was resolved by #166
