### ISSUE TITLE
make chunk_size of openmp parallel regions auto-tunable

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#150]
**Is your feature request related to a problem? Please describe.**
Currently the chunk_size of openmp parallel regions is either not set or not set appropriately.
Often a non-default chunk_size can be very good.

**Describe the solution you'd like**
Make it auto-tunable.

**Describe alternatives you've considered**
Figure it out manually -- check, whether there is some good rule.

**Additional context**
Mostly in traversals.

**Comment by SteffenSeckler** [comment]
can have an impact of factor 2!

**Comment by FG-TUM** [comment]
Shoule be considered in #90

**Comment by SteffenSeckler** [comment]
is already in #90
