### ISSUE TITLE
Test auto tuning with different options missing

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#169]
**Describe the bug**
A test, for the selection of ALL traversal options and ALL container options, is missing.
The test should use a scenario and iterate so long, that all options are tested with all possible variants.
(newton3 and non-newton3)

**Additional context**
- #168 could have been detected.

**Comment by FG-TUM** [comment]
exists:
https://github.com/AutoPas/AutoPas/blob/05a8b0f205124c4e1d588dbd38e357a6ca1d4892/tests/testAutopas/tests/selectors/AutoTunerTest.cpp#L13
