### ISSUE TITLE
Tasked-based traversal(s)

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#179]
**Is your feature request related to a problem? Please describe.**
All current cpu traversals use either openmp parallel fors. We might add some task-based traversals.

**Describe the solution you'd like**
Add task-based traversals

**Describe alternatives you've considered**

**Additional context**
http://www.fz-juelich.de/ias/jsc/EN/Expertise/Workshops/Conferences/CSAM-2015/Programme/lecture7a_gonnet-pdf.pdf?__blob=publicationFile

**Comment by FG-TUM** [comment]
Also think about using [Quicksched](https://gitlab.cosma.dur.ac.uk/swift/quicksched) or OpenMP5 tasks.
My stuff about this using Quicksched:
- [Short range with tasks](https://mediatum.ub.tum.de/1482591)
- [FFM with tasks (MA)](https://mediatum.ub.tum.de/1462318)

**Comment by FG-TUM** [comment]
Currently no direct need for it.
