### ISSUE TITLE
Move neighbor list generation from Container to Traversal

### ISSUE THREAD

**Issue by julian-spahl** [AutoPas/AutoPas#185]
Move aos and soa neighbor lists storeage and generation from VerletLists to Traversals

**Comment by FG-TUM** [comment]
Related:
- #67 <- VerletList container still has no traversals
- #155 <- VerletClusterLists too

**Comment by FG-TUM** [comment]
Save lists still in Container

**Comment by SteffenSeckler** [comment]
close this?

**Comment by FG-TUM** [comment]
yep seems resolved
