### ISSUE TITLE
Test all containers against reference container

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#207]
**Is your feature request related to a problem? Please describe.**
Currently, tests are duplicated a lot and some tests are missing for some containers. 

**Describe the solution you'd like**
There should be a test that tests all possible containers with all possible options for correctness.

**Comment by SteffenSeckler** [comment]
verlet cluster lists is missing

**Comment by FG-TUM** [comment]
@SteffenSeckler I think this can be closed since we test the interface functionality of all containers in `AllContainersTests.cpp` and compare the results of`iteratePairwise()` for all containers in `TraversalComparison.cpp`

**Comment by SteffenSeckler** [comment]
I think so, too.
