### ISSUE TITLE
Conversion to VerletClusterLists can fail

### ISSUE THREAD

**Issue by denizcandas** [AutoPas/AutoPas#208]
**Describe the bug**
When you call md-flexible with --particles-per-dimension=x, where x is not a multiple of 4, the experiment throws the following exception:
terminate called after throwing an instance of 'autopas::utils::ExceptionHandler::AutoPasException'
  what():  LinkedCells: trying to add halo particle that is not in the halo box.

**To Reproduce**
1. compile the program in release mode with openmp enabled
2. call md-flexible with --particles-per-dimension=x, where x!= 0 (mod 4) (edit: also x >4)
3. See error

**Expected behavior**
The experiment finishes without an exception

**Screenshots**
![image](https://user-images.githubusercontent.com/16650999/57516263-b08bc180-7314-11e9-929a-87d86fa65270.png)

**Build environment (please complete the following information):**
 - OS: Linux
 - Compiler: gcc 7.3.0
 - Build System: cmake 3.10.2
- Mpp2 Cluster

**Comment by SteffenSeckler** [comment]
thanks for reporting this.
We are currently working on a proper test to check this behavior. (See branch https://github.com/AutoPas/AutoPas/tree/feature/containerConversion)

For now you can disable the verlet list containers, especially the VerletClusterLists container

**Comment by SteffenSeckler** [comment]
fixed in #209 (except for

**Comment by SteffenSeckler** [comment]
fixed as of #430
