### ISSUE TITLE
Cpp 17

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#211]
**Is your feature request related to a problem? Please describe.**
We would like to bump the C++ Version to 17.
At the Moment this is not possible due to our dependency to CUDA.

**Describe the solution you'd like**
Currently there is none.

**Describe alternatives you've considered**
Both approaches currently do not work:
- NVCC does not support Cpp17
- CMake does not support building CUDA stuff with clang
  https://gitlab.kitware.com/cmake/cmake/issues/16586

**Comment by FG-TUM** [comment]
#194

**Comment by SteffenSeckler** [comment]
fixed through #275
