### ISSUE TITLE
AutoPas::getNumberOfParticles() returns number of saved particles

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#216]
**Describe the bug**
`AutoPas::getNumberOfParticles()` currently returns the total (owned + halo + (dummy)) amount of particles within a container instead of the number particles owned by the container. 

**To Reproduce**
1. Add particles + halo particles to AutoPas. 
2. `getNumberOfParticles()` should then return the number of owned particles

**Expected behavior**
`getNumberOfParticles()` should return the number of owned particles.

**Additional context**
A test should be added for this!

**Comment by FG-TUM** [comment]
Actually owned would make more sense, doesn't it?
Do we maybe need another function to call non-owned?

Also: should it return a saved number (=particle counter) or always count
all particles?
The latter is more time consuming but can be used to detect particle loss.
Suggestion : default to counter but add optional arg to do a full count.
