### ISSUE TITLE
Jenkins: Unstable build, although all build steps passed

### ISSUE THREAD

**Issue by Garfield96** [AutoPas/AutoPas#221]
**Describe the bug**
Although all build steps were successful, Jenkins declares the build as unstable (see screenshot).
This behavior is confusing. Furthermore, if there really is a problem with the build, it is almost impossible to find the origin of the problem.

**To Reproduce**
Check out Jenkins build for branch linked-cells-combine-soa.

**Expected behavior**
At least one yellow marker or a passing build.

**Screenshots**
![unstable_build](https://user-images.githubusercontent.com/15248220/58188498-02d7c580-7cb9-11e9-9541-d066951d020d.png)

**Build environment:**
 - Jenkins

**Comment by SteffenSeckler** [comment]
see http://vmbungartz10.informatik.tu-muenchen.de/mardyn/job/AutoPas-Multibranch/job/linked-cells-combine-soa/

you have a clang warning that needs to be fixed.
