### ISSUE TITLE
AutoPas produces warning if a configuration is enabled even if the functor doesn't allow newton3.

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#222]
**Describe the bug**
If you don't disable Newton3 explicitly via AutoPas::setAllowedNewton3Options and use a functor that doesn't allow newton3, you will spammed by warnings.
Is this intended or would a message in the debug log suffice?

**Comment by SteffenSeckler** [comment]
does this eventually make sense if you use two different functors and one of them is allowing newton3 while the other is not?

**Comment by FG-TUM** [comment]
not valid anymore. No spam happening. :)
