### ISSUE TITLE
TraversalSelector::generateTraversal() has CellPairTraversal as fixed return type, but not all traversals will be CellPairTraversals

### ISSUE THREAD

**Issue by HobbyProgrammer** [AutoPas/AutoPas#229]
**Is your feature request related to a problem? Please describe.**
`TraversalSelector::generateTraversal()` has `CellPairTraversal` as fixed return type, but not all traversals will be `CellPairTraversal`s. Especially the Verlet List traversals will work on neighbor lists, not cells.

**Describe the solution you'd like**
`TraversalSelector::generateTraversal()` should not be limited to `CellPairTraversal`s, but allow all traversals deriving from `TraversalInterface`. This is not straightforward to implement though, as a lot of code depends on it. There are only CellPairTraverals at the moment.

**Describe alternatives you've considered**
Have all traversals derive from `CellPairTraversal`.

**Comment by FG-TUM** [comment]
has to do with `init` and `endTraversal` bein in `CellPairTraversal` but not in the `TraversalInterface`.
Notes:
* `VarVerletTraversalAsBuild` is not a `CellPairTraversal`
* `generateTraversal`
