### ISSUE TITLE
Cobertura Code Coverage broken

### ISSUE THREAD

**Issue by Garfield96** [AutoPas/AutoPas#240]
**Describe the bug**
Jenkins builds all branches with Cobertura code coverage, but results are only visible for the master branch. However, even the master branch only shows the graph and I didn't find a possibility to open a more detailed report. 

**To Reproduce**
check "Coverage Report" in Jenkins for an arbitrary branch (except master)

**Expected behavior**
1. Coverage graphs should be displayed for all branches. 
2. The detailed report should be accessible by clicking on "Cobertura Coverage Report"

**Screenshots**
![Screenshot_20190612_082039](https://user-images.githubusercontent.com/15248220/59327827-045e4180-8ceb-11e9-8950-6a2ede698c37.png)

**Build environment:**
* Jenkins

**Comment by SteffenSeckler** [comment]
The docker image is broken. I rewrote it to sth. non-broken.

**Comment by SteffenSeckler** [comment]
fixed, see:
http://vmbungartz10.informatik.tu-muenchen.de/mardyn/job/AutoPas-Multibranch/job/master/295/cobertura/
