### ISSUE TITLE
Separate traversal interface inheritance from implementation

### ISSUE THREAD

**Issue by HobbyProgrammer** [AutoPas/AutoPas#297]
**Is your feature request related to a problem? Please describe.**
Currently, we have `TraversalInterface` as interface for all traversals, and `CellPairTraversal` or `CBasedTraversal` as common class for similar traversals that iterate somehow over cells. The first one is interface (or specification) inheritance, while the last one is implementation inheritance. [C++ Core Guidelines: C.129](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c129-when-designing-a-class-hierarchy-distinguish-between-implementation-inheritance-and-interface-inheritance) states that it is good practice to separate implementation inheritance from interface inheritance, but in our code, `CellPairTraversal` inherits from `TraversalInterface` without implementing a single method specified in `TraversalInterface`. 

**Describe the solution you'd like**
I would like to have implementation and interface (specification) inheritance separated in the traversal hierarchy by removing the inheritance relationship between `CellPairTraversal` and `TraversalInterface`. The traversal interfaces for each container (e.g. `LinkedCellsTraversalInterface`) could inherit from `TraversalInterface` instead, as they are also mostly interface (specification) inheritance.

**Describe alternatives you've considered**
Leave it like it is.

**Comment by FG-TUM** [comment]
We don't see this as a significant issue right now and refactorings coming in with three body interactions will change the inheritance relations anyways.
