### ISSUE TITLE
Old rebuild frequency implicitly converted to cell size factor

### ISSUE THREAD

**Issue by HobbyProgrammer** [AutoPas/AutoPas#313]
**Describe the bug**
Since removing `rebuildFrequency` and adding `cellSizeFactor`, there are some constructor calls in which the old rebuild frequency is converted to the cell size factor.

**To Reproduce**
https://github.com/AutoPas/AutoPas/blob/c1c6b1bfcfe732f5ce0d595e97a77fabcaf18f04/examples/sph-traversals/sph-traversals.cpp#L114-L119

I think it is necessary to check the rest of the code base if that happens elsewhere, too.

**Expected behavior**
The cell size factor should probably be the default value and rebuild frequency should be removed everywhere.

**Comment by SteffenSeckler** [comment]
resolved as of #330
