### ISSUE TITLE
C04SoA conflicts with MockFunctor

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#318]
**Describe the bug**
When executing the Newton3OnOffTest for C04SoA the following happens:

* In the Traversal SoAViews are generated:
https://github.com/AutoPas/AutoPas/blob/043c38a20ed883aedc2c0b9321d177395c070405/src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h#L252

* The size of the view is defined by offsets which were calculated based on the content of the cells:
https://github.com/AutoPas/AutoPas/blob/043c38a20ed883aedc2c0b9321d177395c070405/src/autopas/containers/linkedCells/traversals/C04SoACellHandler.h#L450-L451

* Since in this test we use the MockFunctor it does not actually load any particles in the SoA Buffers. Therefore any sanity check that compares the start / end of a view to the actual size of the SoA will fail, even in the constructor of the SoAView.

**To Reproduce**
1. Go to branch #299
2. Remove comments around exception if in the Constructor.
2. Run `ctest -j12 -R 'Newton3OnOff.*c04SoA.*of-A.*' --verbose`
3. Get slapped by this very exception.

**Expected behavior**
No exception :)

**Ideas / possible Solutions**

* We Mock away more so the actual SoAView constructor is not called
* Offsets are calculated by whats actually in the SoAs
* We remove the sanity check **<- not a good option**

**Comment by FG-TUM** [comment]
@Garfield96 this might interest you

**Comment by HobbyProgrammer** [comment]
Another solution might be to resize the `SoA` to the appropriate size in the Mock `SoALoader` . I haven't done this with googlemock yet, but it should be possible, right?
