### ISSUE TITLE
VarVerletListsAsBuild uses way too much memory

### ISSUE THREAD

**Issue by HobbyProgrammer** [AutoPas/AutoPas#322]
**Describe the bug**
The `VarVerletListsAsBuild` container uses way to much memory with data layout SoA and many threads.

**To Reproduce**
1. Start a simulation with the container, SoA, and many threads.
2. See that the memory usage scales with the number of threads and way to high.

**Expected behavior**
The memory usage should be more or less equal for different numbers of threads.

**Comment by HobbyProgrammer** [comment]
I now remember what the problem with this configuration was. When writing the SoA stuff for that configuration, I noticed the problem, but didn't write it down somewhere, sadly. I think I have briefly mentioned it the @FG-TUM, but wasn't aware how big of a problem it is, then.

An important part of the problematic configuration with `VarVerletListsAsBuild` is that is needs only way to much memory, when many threads are used. 

The reason for this is the type of the neighbor list the `SoAFunctor` for neighbor lists accepts. This is `std::vector<std::vector<size_t, autopas::AlignedAllocator<size_t>>>`. Here, the index of the outer vector is the index of the first particle in the pair to work on in the SoA, and the inner vector contains the indices of all neighbors of this first particle in the SoA.

The problem with this type of the neighbor list and the approach of the `VarVerletListsAsBuild` is that there has to exist one neighbor list of this type per color and per thread, and that, by definition of the type, the neighbor list always contains the neighbors for all particles in the whole container. This leads to an incredible amount of empty vectors, since all of the neighbor lists actually partition the particles, and no neighbor list contains neighbors for all particles.

For AoS, the problem does not exist since I internally of course don't use this type for the neighbor list, but a `std::unordered_map` that only contains entries for the particles the neighbor list really saves neighbors for.

As I see it, there are two approaches to solving this:
 1. We can somehow try to generate this type of neighbor list on the fly during the traversal. This would cost performance, but would, in the ideal case, divide the memory necessary by the number of colors used (8), since each thread only has one of these neighbor lists in the memory at the same time.
2. We change the type of the neighbor list in the `SoAFunctor`, or add a new method in `Functor` that accepts another type of neighbor list that can only contain the neighbors for a part of the given SoA.

What do you think about that?

**Comment by HobbyProgrammer** [comment]
For approach 2:
The signature of the `SoAFunctor` could be changed from 
`void(SoAView<SoAArraysType> &soa, const std::vector<std::vector<size_t, autopas::AlignedAllocator<size_t>>> &neighborList, size_t iFrom, size_t iTo)`
to
`void(SoAView<SoAArraysType> &soa, size_t firstIndex, const std::vector<size_t, autopas::AlignedAllocator<size_t>> &neighborList)`,
where `firstIndex` is the index of a particle and `neighborList` contains the indices of all neighbors of the particle.

This would need only minimal changes of the implementations of the `Functor` and the callers.

**Comment by FG-TUM** [comment]
@HobbyProgrammer please tag your future PR with this issue.
