### ISSUE TITLE
Remove redundant Template Arguments

### ISSUE THREAD

**Issue by Garfield96** [AutoPas/AutoPas#323]
**Is your feature request related to a problem?**
Template classes often require the `Particle` and the `ParticleCell` type. Currently, most of the classes have both types as template arguments, but the `Particle` type is already defined by the cell. The current implementation leads to extremely long types, which makes especially debugging more difficult.

**Describe the solution you'd like**
Remove the `Particle` type from the template list and use the `Particle` type of the cell. 

**ToDo**
The following classes still need to be done:
* iterators: 
  * [ ] ParticleIterator
  * [ ] RegionParticleIterator
  * [ ] SingleCellIterator

* pairwiseFunctors:
  * [ ] CellFunctor
  * [ ] FlopCounterFunctor
  * [ ] Functor
  * [ ] LJFunctor
  * [ ] LJFunctorAVX
* selectors:
  * [ ] AutoTuner
  * [ ] ContainerSelector
* [ ] AutoPas interface

**Comment by HobbyProgrammer** [comment]
You mean `Particle` and `ParticleCell`, right? That would be really cool!

**Comment by Garfield96** [comment]
> You mean `Particle` and `ParticleCell`, right? That would be really cool!

Yes, you are right. I corrected the Issue description.

**Comment by SteffenSeckler** [comment]
what is still missing here?

**Comment by Garfield96** [comment]
> what is still missing here?

@SteffenSeckler In PR #338 all redundant arguments inside the `containers` folder were removed. The following classes still need to be done:
* iterators: 
  * [ ] ParticleIterator
  * [ ] RegionParticleIterator
  * [ ] SingleCellIterator

* pairwiseFunctors:
  * [ ] CellFunctor
  * [ ] FlopCounterFunctor
  * [ ] Functor
  * [ ] LJFunctor
  * [ ] LJFunctorAVX
* selectors:
  * [ ] AutoTuner
  * [ ] ContainerSelector
* [ ] AutoPas interface

**Comment by FG-TUM** [comment]
relevant PR: #444

**Comment by FG-TUM** [comment]
closed via #444
