### ISSUE TITLE
Jenkins: Update grep version

### ISSUE THREAD

**Issue by Garfield96** [AutoPas/AutoPas#341]
**Is your feature request related to a problem?**
The current version of grep used in Jenkins does not allow to specify which file types should be checked. Currently, this problem is solved by filtering the file types in a second step, which causes unnecessary overhead and is not elegant.

**Describe the solution you'd like**
Update grep to a version which supports `--include` to only check relevant files.

**Describe alternatives you've considered**
Stay with the old solution.

**Comment by SteffenSeckler** [comment]
this is inside of the official jenkins slave alpine image, which I do not really want to touch.
