### ISSUE TITLE
Verlet List vectorization

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#35]
**Is your feature request related to a problem? Please describe.**
Verlet-Lists (#10) currently does not use vectorization.

**Describe the solution you'd like**
Implement vectorization.
* build SoA globally.
* probably different interface for SoALoader, SoAExtractor

Problems:
* SOALoader, SOAExtractor currently are cell-based
* SOA has to be updated when haloparticles are updated

**Describe alternatives you've considered**

**Additional context**
> very cool :)
> how does it look like with vectorization? This paper discusses simple LJ Verlet list implementation with intrinsics, maybe you can look at it:
> https://software.intel.com/sites/default/files/article/478279/mxhmd.final.pdf
> 
> Also, in LAMMPS, the Verlet lists are vectorized with compiler pragmas only (I think) and the code is more or less readable. You can look at it in void PairLJCutIntel::eval(...) here:
> https://github.com/lammps/lammps/blob/master/src/USER-INTEL/pair_lj_cut_intel.cpp
> 
> Best,
> Nikola

**Comment by SteffenSeckler** [comment]
@FG-TUM @tchipev 
I was able to get the performance of the kernel call to around 50% more than the one from the AoS version. The main problem seems to be the memory access and storing of the forces.
I tested this on a an machine with AVX2, so scatter is not available.

main code is here:
https://github.com/AutoPas/AutoPas/blob/762d910f5191b866fd515bef0746167a3859924b/src/pairwiseFunctors/LJFunctor.h#L201-L334
(Verlet-List-Vectorization Branch)

**Comment by tchipev** [comment]
Hi,
yeah, gcc considers a reduction operation to be unsafe and refuses to vectorize the clause
#pragma omp simd reduction

` The main problem seems to be the memory access and storing of the forces.`
You can try disabling Newton's third law optimization by a template argument of the (backend) function call.

**Comment by SteffenSeckler** [comment]
fyi:

aos/soa | part | FU | time[s] | MFUPS | FLOPs | hitrate | GFLOP/sec
--- | ----- | --- | --- | --- | --- | --- | ---
aos | 8192 | 100 | 0.899502 | 0.910726 | 2.31116e+09 | 1 | 2.56937
soa | 8192 |	100 |	0.663648 |	1.23439	| 2.31116e+09 |	1	|3.4825	

single core, kernel only (no rebuilding of verlet lists)

**Comment by SteffenSeckler** [comment]
some work by #49
