### ISSUE TITLE
deletion of particles does not set VerletLists::_neighborListIsValid to false

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#37]
**Describe the bug**
deletion of particles does not set VerletLists::_neighborListIsValid to false

**To Reproduce**

**Expected behavior**
deletion of particles should set VerletLists::_neighborListIsValid to false

**Problems**
a) thread safety
b) the iterators don't know their parent container

**Additional context**
ref #10

**Comment by FG-TUM** [comment]
not applicable anymore.
