### ISSUE TITLE
internal helpers for verlet-list halo exchange

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#39]
**Is your feature request related to a problem? Please describe.**
When doing the verlet-lists should be reused the halo exchange has to update the exact same halo particles in each step until the verlet-lists are rebuild.
Currently the user has to save which particles he send in the step where the verlet-lists were first generated and then send precisely these particles again. It would be helpful, if there were some way to ease this.

**Describe the solution you'd like**
The iterators should be saved internally. This could work in the following way:
The user provides a sort of tag to identify the iterator that should be reusable.
The traversed particles should then be saved internally (by pointer), when iterating through the particles. This should happen, if a rebuild is necessary.
If a rebuild is not necessary the saved list of particles should be used as iterator.

**Describe alternatives you've considered**
* Don't provide it internally.
* other ideas?

**Additional context**
Some problems:
* thread safety of the saving of the iterator?

**Comment by FG-TUM** [comment]
by now this is invalid.
Halo exchange works like this:

https://github.com/AutoPas/AutoPas/blob/05a8b0f205124c4e1d588dbd38e357a6ca1d4892/tests/testAutopas/tests/autopasInterface/AutoPasInterfaceTest.cpp#L148-L171
