### ISSUE TITLE
VerletClusterCells::rebuild() creates segfault when particles are too far outside the domain

### ISSUE THREAD

**Issue by Jakob-en** [AutoPas/AutoPas#393]
**Describe the bug**
In VerletClusterCells::rebuild() when particles are too far outside the domain, an invalid cell index is calculated resulting in a segmentation fault.

**To Reproduce**
Execute md-flexible with VerletClusterCells as only container option.
`./md-flexible --container VerletClusterCells`

**Comment by SteffenSeckler** [comment]
can reproduce this, will look into it, when I have time
