### ISSUE TITLE
LJFunctors do not yet support SoA for VerletClusters correctly.

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#396]
**Is your feature request related to a problem? Please describe.**
The LJFunctors does not yet support SoA, as the functor calls do not correctly handle the global calculations, as the owned state is not used.

**Describe the solution you'd like**
Use the owned state correctly.

**Additional context**
Once this is done:
- [ ] enable the calculation in LJFunctor::isAppropriateClusterSize(), as that function is currently disabling the SoA functionality.

**Comment by FG-TUM** [comment]
This issue refers to VerletCluster**Cells** (=CUDA) and not VerletCluster**Lists**.
