### ISSUE TITLE
Parallel Tuning Strategies

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#410]
**Is your feature request related to a problem? Please describe.**
Currently, AutoPas always searches in each rank through the entire search space.
If a completely homogeneous domain is used one could parallelize this search over multiple AutoPas instances.

**Describe the solution you'd like**
- [x] MPI-parallel Full-Search
- [x] Parallel search independent of tuning-strategy
- [x] Parallel search with Active Harmony
- [x] Inhomogeneous domains
  - [x] Normalization?
  - [x] Clustering of similar AutoPas instances for comparison.
- Compare:
  - [ ] Test similar configurations on same ranks (less switching)
  - [ ] Test different configurations on same ranks (better load balancing?)

**Comment by SteffenSeckler** [comment]
clustering:
can potentially be done by actual 2d clustering by measuring the speed for each process for e.g. one static and one dynamic linked cells traversal

**Comment by wothie** [comment]
Considering a combination of "Parallel search independent of tuning-strategy" and "Parallel search with Active Harmony" by just providing a utils header with all necessary (and as general as possible) MPI functionalities regarding configurations, search spaces, finding optima, etc.
This would best work by changing the search spaces to std::vector and providing additional iterators  for tuning strategies not based on search spaces.

**Comment by FG-TUM** [comment]
closed as completed with the PRs linked above
