### ISSUE TITLE
Cuda: LJFunctors throw exceptions at VERY high densities

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#419]
**Describe the bug**
Both LJFunctorCuda and LJFunctorCudaGlobals throw the exception
```
C++ exception with description "Linked Cells NoN3: cuda Kernel size not available for Linked cells. Too many particles in a cell. Requested: 1024" thrown in the test body.
```
if there are too many particles in a cell. It would be nice to be able to support this, too.

**To Reproduce**
1. Remove if condition in TraversalComparison and run tests with enabled cuda.
```c++
if (dataLayoutOption == autopas::DataLayoutOption::Value::cuda and
    traversalOption == autopas::TraversalOption::Value::c01Cuda and boxMax[0] < 5. and
    numParticles > 500) {
  continue;
}
```
2. run tests

**Comment by FG-TUM** [comment]
This issue refers to VerletClusterCells (=CUDA) and not VerletClusterLists.
