### ISSUE TITLE
C01CudaTraversal is incorrect when using Newton3 and Halo Particles are present

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#420]
**Describe the bug**
The C01CudaTraversal is not correctly adapted for enabled newton3 with present halo particles.
If newton3 is enabled, the offsets are currently changed, s.t., only positive offsets are used.
This results in a wrong behavior as the iteration of the base step only iterates over inner cells.
Interactions between cells in the lower parts of the domain are ignored.

**To Reproduce**
1. Reenable the traversal for newton3
2. Run TraversalComparison
3. Observe error

**Expected behavior**
Produces same results.

**Additional context**
Minimal example:
```c++
container->addParticle(autopas::MoleculeLJ({0.24923935078514708, 3.6499270906904373, 7.6538098220032689}, {0., 0., 0.}, 0));
container->addHaloParticle(autopas::MoleculeLJ({-0.24923935078514708, 3.6499270906904373, 7.6538098220032689}, {0., 0., 0.}, 1));
```

**Comment by FG-TUM** [comment]
#614 made this obsolete
