### ISSUE TITLE
clang openmp-simd does not compile in sequential mode (OPENMP disabled)

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#43]
**Describe the bug**
Clang compiler can not compile sequential, vectorized version of AutoPas.

**To Reproduce**
1. checkout feature/clang-vectorization
2. `CC=clang CXX=clang cmake ..`
3. make

will give you errors like:
```
main.cpp:(.text._ZN7autopas15SlicedTraversalINS_16FullParticleCellI17PrintableMoleculeEENS_11CellFunctorIS2_S3_NS_7FunctorIS2_S3_EELb0ELb0EEEE17traverseCellPairsEv[_ZN7autopas15SlicedTraversalINS_16FullParticleCellI17PrintableMoleculeEENS_11CellFunctorIS2_S3_NS_7FunctorIS2_S3_EELb0ELb0EEEE17traverseCellPairsEv]+0x39c): undefined reference to `omp_unset_lock'
```
or
```
../src/utils/WrapOpenMP.h:21:10: fatal error: 'omp.h' file not found
```
**Expected behavior**
compiles normally

**Build environment (please complete the following information):**
 - OS: Linux
 - Compiler: clang 6.0
 - Build System: all

**Additional context**
The clang compiler defines _OPENMP if compilation is done with -fopenmp-simd, even if -fopenmp is not specified. Adding -fno-openmp does not help in this context. _OPENMP will still be defined.
From my perspective, this is a clear compiler bug, as _OPENMP should only be defined if the program has been compiled with -fopenmp.

I will file a bugreport at llvm.org and link it here once it is created.
See also:
http://vmbungartz10.informatik.tu-muenchen.de/mardyn/blue/organizations/jenkins/AutoPas-Multibranch/detail/feature%2Fclang-vectorization/1/pipeline

**Comment by SteffenSeckler** [comment]
llvm bug:
https://bugs.llvm.org/show_bug.cgi?id=37536

**Comment by SteffenSeckler** [comment]
fyi: fixed in
https://github.com/llvm-mirror/clang/commit/5f1f5eacd8f7d864f8d966c5f61f3d3d6ef2218d

might be in 6.0.1 release, but I'm not sure.

**Comment by SteffenSeckler** [comment]
we could implement a workaround, s.t. we can compile that configuration also with affected versions of clang:
```
#ifdef _OPENMP
```
would have to be replaced with:
```
#ifdef AUTOPASOPENMP
```
and AUTOPASOPENMP should be defined appropriately. Either in an extra file, or simply in the cmake config.

@FG-TUM what are your thoughts on this?

**Comment by FG-TUM** [comment]
Since it is a compiler bug I would intuitively fix it via cmake to keep the actual code cleaner.
Either `OpenMP.cmake` or if we keep finding compiler bugs s.th. like `CompilerBugs.cmake` ;)
