### ISSUE TITLE
remove iterators and replace with for_each, parallel_for_each, parallel_reduction, ...

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#434]
**Is your feature request related to a problem? Please describe.**
Needed for proper kokkos support.
Also makes our lives easier

**Comment by SteffenSeckler** [comment]
particle deletion will probably become more complicated that way and probably needs an additional method.
This would also solve #435.

**Comment by SteffenSeckler** [comment]
or, probably also needed for the LC-reference-cell container (tentative name) just flag a particle as deleted and delete them only later.

**Comment by LG-TUM** [comment]
I will add a parallel_for_each in a future commit for #626 
This will however just be calling the sequential for_each, until kokkos is integrated.

Additionally, examples (eg. md-flex) will be adapted in a future mr.

**Comment by FG-TUM** [comment]
I would actually like to use `_parallel` as a suffix in all of these names.

**Comment by LG-TUM** [comment]
> I would actually like to use `_parallel` as a suffix in all of these names.

Camel cased or with underscore?

so forEachParallel or forEach_parallel ?

**Comment by FG-TUM** [comment]
Right, probably `forEachParallel` for consistency ;)

**Comment by LG-TUM** [comment]
On the topic of reductions:
Is there a necessity for "region reductions"?
Or are reductions currently (and in the future) always performed on all particles (still considering IteratorBehavior).

**Comment by FG-TUM** [comment]
Good question. I would assume reductions only of a subset of particles are also of interest.

**Comment by LG-TUM** [comment]
I know how to trigger your sense of creating Arbeitsbeschaffungsmaßnahmen and should probably stop right?

**Comment by FG-TUM** [comment]
I'd say just start implementing them, and when you notice that there is a huge overlap of code try to remove redundancies e.g. via templates or calls to helper functions.

**Comment by SteffenSeckler** [comment]
question: how are parallel foreachs named in kokkos or other codes? does it maybe make sense to use a similar naming scheme?

**Comment by LG-TUM** [comment]
> question: how are parallel foreachs named in kokkos or other codes? does it maybe make sense to use a similar naming scheme?

parallel_for and parallel_reduce
https://github.com/kokkos/kokkos/wiki/ParallelDispatch
