### ISSUE TITLE
VerletClusterLists should use a proper CellBorderAndFlagManager when possible

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#437]
**Is your feature request related to a problem? Please describe.**
Currently, we use the UnknowingCellBorderAndFlagManager for the VerletClusterLists.
This can be optimized.

**Describe the solution you'd like**
Use a proper CellBorderAndFlagManager
This will make it possible to optimized, especially, iteration over HaloParticles.

**Describe alternatives you've considered**
More or less invalid, if #434 is implemented.

**Additional context**
workaround (using the Unknowing...) was introduced in #430

**Comment by FG-TUM** [comment]
As of #712 VCL doesn't even use the `UnknowingCellBorderAndFlagManager` anymore as it is not relevant anymore for iterators.

**Comment by FG-TUM** [comment]
Should have Bern closed with the merge of #712
