### ISSUE TITLE
Predictive Tuning

### ISSUE THREAD

**Issue by julianpelloth** [AutoPas/AutoPas#439]
**Is your feature request related to a problem? Please describe.**
Currently, AutoPas calculates every possible configuration and selects the fastest for the next N iterations.

**Describe the solution you'd like**
The performance of the configuration should be predicted through extrapolation and only those who are predicted to be near the optimum should be tested.

**Comment by SteffenSeckler** [comment]
this should be added as an additional tuning strategy.
