### ISSUE TITLE
Log-file bug in md-flexible

### ISSUE THREAD

**Issue by julianpelloth** [AutoPas/AutoPas#458]
**Describe the bug**
When a log-file is given in the user input, the output is still in the console and the file is empty.

**To Reproduce**
1. Build md-flex
2. run md-flex with --log-file anyFileName --log-level debug
3. See that output is in console and file is empty

**Expected behavior**
The output of the logger should be in the given filename.

**Possible explentation**
The file name is never given to the AutoPas object and therefore not output can be written in it.
The file name needs to be given with the initiation of the AutoPas object or it has to be changed after the initiation.

**Comment by FG-TUM** [comment]
got it fixed in #451
