### ISSUE TITLE
CellBlock3D::getCellBoundingBox() functions should return results instead of writing them in parameters.

### ISSUE THREAD

**Issue by lunaticcoding** [AutoPas/AutoPas#473]
**Describe the bug**
CellBlock3D::getCellBoundingBox() should return a pair instead of setting two out parameters.

**Expected behavior**
Should return a pair.

**Comment by SteffenSeckler** [comment]
which function is this, actually?

**Comment by lunaticcoding** [comment]
@SteffenSeckler should be `this->getCellBlock().getCellBoundingBox(cellId, cellLowerCorner, cellUpperCorner);`
