### ISSUE TITLE
md-flexible does not apply periodic boundaries consistently

### ISSUE THREAD

**Issue by VincentF98** [AutoPas/AutoPas#495]
**Describe the bug**
When running a Simulation with md-flexible and periodic boundaries, the particles in the final vtk file are not always within the bounding box.

**To Reproduce**
1. run md-flexible using the provided SpinodalDecomposition_equilibration.yaml file

**Expected behavior**
All particles in the final vtk file are within the bounding box.

**Build environment (please complete the following information):**
* OS: x86_64 GNU/Linux
* Compiler: clang 9
* Build System: cmake + make

**Additional context**
This leads to an error when running the actual simulation (SpinodalDecomposition.yaml)
```
terminate called after throwing an instance of 'autopas::utils::ExceptionHandler::AutoPasException'
  what():  Trying to add a particle that is not in the bounding box.
Particle
ID      : 2886
Position: 231.646 | 10.9868 | -0.751177
Velocity: 1.25434 | -0.893271 | -1.04666
Force   : 2.80984 | -0.435455 | 3.67645
/var/slurmd-cm2_tiny/job17436/slurm_script: line 18: 23303 Aborted                 (core dumped) ./md-flexible --yaml-filename SpinodalDecomposition.yaml --log-level debug

```

**Comment by FG-TUM** [comment]
fixed by #526
