### ISSUE TITLE
Same simulation is much slower in comparison to an older commit

### ISSUE THREAD

**Issue by julianpelloth** [AutoPas/AutoPas#519]
**Describe the bug**
The same simulation, perfTest_inhomo.yaml, takes more that double the time it took with an older commit.

**To Reproduce**
1. Go to branch feature/change-testing-of-bad-predictions .
2. Start simulation pertTest_inhomo.yaml. Output:
![badSimulationYaml](https://user-images.githubusercontent.com/62945826/88836433-f57c6c00-d1d6-11ea-9e05-36cbe7e0c8f4.png)

3. See duration of the simulation:
![badSimulation](https://user-images.githubusercontent.com/62945826/88835753-037dbd00-d1d6-11ea-89d7-cbb1312c57dc.png)

**Expected behavior**
1. Go to commit  a3193c3.
2. Start simulation pertTest_inhomo.yaml. Output:
![goodSimulationYaml](https://user-images.githubusercontent.com/62945826/88836490-0fb64a00-d1d7-11ea-9dc3-1118ae919bbc.png)

3. See duration of the simulation:
![goodSimulation](https://user-images.githubusercontent.com/62945826/88836586-31173600-d1d7-11ea-83dd-fd1ed29ee480.png)

**Additional information**
Simulation run on the CoolMuc2 with the following job script:
![jobScript](https://user-images.githubusercontent.com/62945826/88837104-0bd6f780-d1d8-11ea-82c7-b3edcfafed82.png)

**Comment by SteffenSeckler** [comment]
@kruegener can you generate a plot for that? Pretty please :)

**Comment by kruegener** [comment]
> @kruegener can you generate a plot for that? Pretty please :)

On it ;)

**Comment by kruegener** [comment]
Running Performance Comparisons overnight.
This e.g. is a comparison between the current master and the first commit in feature/change-testing-of-bad-predictions c58493d
Comparison: https://github.com/AutoPas/AutoPas/runs/933868121
Raw Results: https://github.com/AutoPas/AutoPas/runs/933868111

These tests for all commits in this PR #508 should be done by morning.

The new default is to test the change in performance by merging the feature branch and master branch, but the merge is failing for this commit (and basically the entire branch), same as on Jenkins.

I'm also running measurements on a3193c3 and will compare to the feature branch as well as current master once they are done.

**Comment by kruegener** [comment]
Part of the issue is almost certainly related to variance in the test results, as some containers only run for a very brief amount of time.
This is the same commit, compared against itself having run the same performance script twice.

Homo Case:
![newplot (1)](https://user-images.githubusercontent.com/19388631/89357127-e8241d80-d6bf-11ea-994b-632cbc08172c.png)

In-Homo Case:
![newplot (2)](https://user-images.githubusercontent.com/19388631/89357263-47822d80-d6c0-11ea-971e-a581ee7ddbc2.png)

**Comment by SteffenSeckler** [comment]
just checked the new dashboard:
http://plotly.pproc-be.sccs.in.tum.de/

https://github.com/AutoPas/AutoPas/pull/492/commits/78d6de1cef55b3f8bed9ee47703a0df9014d4167 seems to be the "issue". So all ok.
