### ISSUE TITLE
IteratePairwiseAoS2 and iteratePairwiseSoA2 should always be called

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#52]
**Describe the bug**
`iteratePairwiseAoS2` and `iteratePairwiseSoA2` should always be called instead of
`iteratePairwiseAoS` and `iteratePairwiseSoA` should always be called.
The functions with a `2` provide a method to call the functions using the functor as template argument.

This can only be done if the type of the particle container is known.

**Suggestion**
completely remove the interface of `iteratePairwiseAoS` and `iteratePairwiseSoA` and identify the different containers on runtime, but with a static decision tree:

```C++
template<class Functor>
void AutoPas::iteratePairwise2(Functor *f, autopas::DataLayoutOption dataLayoutOption) {
  ...
  if (auto &cont = dynamic_cast<VerletLists<Particle, ParticleCell> &>(*container)) {
    cont.iteratePairwise2(...);
  }
  else if (auto &cont = dynamic_cast<LinkedCells<Particle, ParticleCell> &>(*container)) {
    cont.iteratePairwise2(...);
  }
  else if (auto &cont = dynamic_cast<DirectSum<Particle, ParticleCell> &>(*container)) {
    cont.iteratePairwise2(...);
  }
}
```
this here more or less ignores the other things (dataLayoutOption, soa, aos, newton3, ...) so to make it somewhat feasible some template magic might be required to get the in-lining done without too much code.

**Comment by FG-TUM** [comment]
I came about this too the other day. I will try out some things in the strategySelectors branch.
