### ISSUE TITLE
lc_combined* Traversals segfault with AVX Functor

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#535]
**Describe the bug**

When using the lc_combined (`lc_c04_combined_SoA` and `lc_c01_combined_SoA` traversals in combination with the intrinsics functor sometimes segfaults happen in memory load operations.

**To Reproduce**
`md-flexible --no-end-config --no-flops --functor lennard-jones-AVX2 --deltaT 0 --particle-generator uniform --log-level debug --traversal lc_c04_combined_SoA  --particles-total 71`

**Expected behavior**
No segfault 🙃 

~**Screenshots**~

**Build environment (please complete the following information):**
* OS: WSL, CooLMUC2
* Compiler: (e.g. gcc 9, clang 11)
* Build System: make

**Additional context**
This might be due to these traversals not using SoAs directly but views. These views work as offsets from normal views which might break the alignment...?

**Comment by SteffenSeckler** [comment]
I can confirm that replacing `load`s and `store`s with `loadu`s and `storeu`s (the unaligned variants of those intrinsics) fixes this problem.
So this definitely is an alignment problem.

I'll create a PR with this stupid fix. Probs should be implemented as a template argument, or so.
