### ISSUE TITLE
Test with AUTOPAS_MPI=On

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#554]
**Is your feature request related to a problem? Please describe.**
Jenkins does not include a test with enabled AUTOPAS_MPI. In fact, those tests are partially failing.

**Describe the solution you'd like**
Add test with AUTOPAS_MPI=On to Jenkinsfile and fix tests.

**Comment by FG-TUM** [comment]
Related to #641

**Comment by FG-TUM** [comment]
Still true after migrating from Jenkins to GitHub workflows.

**Comment by FG-TUM** [comment]
Currently, we only run the examples tests with MPI but not the regular unit tests. We should at least run the stuff from `tests/MPIParallelAutoPasTests`.
