### ISSUE TITLE
varying cutoffs for sph

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#6]
Allow varying cutoffs for sph. This probably has to be done after issue #5 
we might need an extra container for that, as this probably does not provide the best performance results for Linked-Cell containers.

**Comment by FG-TUM** [comment]
as long as further cutoffs in functors are smaller than the one set in the autopas main interface this should work.

**Comment by SteffenSeckler** [comment]
fyi: this is not supported within the sph functor provided inside of AutoPas
