### ISSUE TITLE
Switch to 32-bit floating point precision in md-flexible gives compilation errors

### ISSUE THREAD

**Issue by HobbyProgrammer** [AutoPas/AutoPas#600]
**Describe the bug**
According to the comment, using float instead of double for md-flexible should be as easy as changing the type here:
https://github.com/AutoPas/AutoPas/blob/afd607d0be64f4a4a135f041c0936b059e5b8bc1/examples/md-flexible/src/TypeDefinitions.h#L12-L15
This is not the case. Changing this gives compilation errors. Listing all compilation problems here does not make sense, it is kind of a bottomless pit. However, they aren't limited to md-flexible code, but also in the AutoPas library itself. 

**To Reproduce**
1. Change to the type from `float` to `double`.
2. Compile.

**Expected behavior**
The compilation should not fail.

**Comment by SamNewcome** [comment]
Closed as not considered important for the foreseeable future.
