### ISSUE TITLE
move autopas src

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#69]
**Describe the bug**
autopas sources should be moved, s.t. all sources are in:
src/autopas/

this changes the include path from
```C++
#include "AutoPas.h"
```
to
```C++
#include "autopas/AutoPas.h"
```
as it should be done according to xsdk and other guidelines.

**Comment by SteffenSeckler** [comment]
to be done once no pull requests are open

**Comment by FG-TUM** [comment]
done
1e7a57442d507805fabe71368ec1c58c7354710f
