### ISSUE TITLE
Particle out of box during fallingDrop simulation

### ISSUE THREAD

**Issue by pandeddy** [AutoPas/AutoPas#713]
The simulation of fallingDrop interrupts with an runtime_error (particle out of the box)

**To Reproduce**
  run ./md-flexible --yaml-file fallingDrop.yaml in the build directory

**Expected behavior**
  particle should be reflected of the boundaries and the simulation should run without an error.

**Screenshots**
![Screenshot from 2023-01-25 11-43-21](https://user-images.githubusercontent.com/109224502/214554896-f360355c-0409-4bfc-a75b-0c91e88b2158.png)

**Build environment:**
OS: Linux

**Comment by SamNewcome** [comment]
I did some digging, basically, the reflecting boundaries I implemented are not good enough. The assumption was that if you can ensure that a particle will pass through a reflective skin and you reverse the velocity when it's in the reflective skin then the particle will not pass beyond the boundary. And so if fastParticleThrow is never thrown, no particle can escape the boundary. But, for the position update, if the force contribution is greater than the velocity contribution, the particle can still move towards and beyond the boundary. This seems to be particularly the case for scenarios where you have a basin of molecules held down by a global force and held up by a reflecting boundary. There are a couple of solutions:

1. Ask the user to reduce deltaT. The force contribution to the position update is O(dt^2) whereas the velocity contribution is O(dt), so there should be a step size which is small enough that the reflected velocity contribution can always overpower the force contribution. This is a hacky solution, as this suitable deltaT may be very small.
2. Reflect the force as well as velocity. But I'm concerned that this will lead to unphysical results, but this is certainly an easy fix for now.
3. Set the force to 0 when the velocity is to be reflected.
4. Implement ghost particle reflections. If deltaT is small enough, the particle should receive a force back into the domain that can overcome the global force before it reaches the boundary. I would expect, unless the global force is far bigger than the typical intermolecular forces, that we should be using an appropriate deltaT to begin with.



@pandeddy I would suggest, for now you reduce deltaT. You can also reduce the verlet-skin-per-timestep at the same time. I will try to implement fix (2) or (3) asap, and hopefully this is a good enough fix for the short term.

@FG-TUM which of (2) or (3) do you suspect to produce better results?

Long term, I /  somebody else should implement fix (4), but this may not happen immediately.
