### ISSUE TITLE
YamlParser::parseYamlFile() is missing if statement for vtk-output-file

### ISSUE THREAD

**Issue by TumBeat** [AutoPas/AutoPas#740]
**Describe the bug**
It seems like the `parseYamlFile()` has no if-else statement for "vtk-output-folder". `MDFlexConfig.h` has a definition for the `vtkOutputFolder` property (see screenshot) but at the moment this variable is only read and never changed.
When trying to set a custom output folder via `vtk-output-folder` in a yaml file, the attached error message occurs saying that this option was not recognized (see screenshot).

**To Reproduce**
Add a line
`vtk-output-folder   : myFancyFolder`
to a chosen input yaml file and run the md-flexible program with this input file.

**Expected behavior**
The specified output folder from the yaml-file should be read and used.

**Screenshots**
Config in `MDFlexConfig.h`
![MDFlexConfig](https://user-images.githubusercontent.com/111445698/235192169-48bc9734-23e2-4322-9e4d-2f1e09a073f6.png)
Error message
![Yaml-issue](https://user-images.githubusercontent.com/111445698/235191885-8bb9982b-474f-4624-8231-12cb6a698be2.png)

**Build environment (please complete the following information):**
* OS: Linux Cluster, LRZ
* Compiler: gcc 11.2.0
* Build System: CMake

**Comment by TumBeat** [comment]
I'm already on it.
I need the feature of setting a custom output folder for running the md-flexible code on the linux cluster to specify that the output folder is $SCRATCH. Just stumbled accros this when I was just trying to test something there.
But I agree, in general the importance is kind of low and for now, I can use the command line for specifying this :D

**Comment by FG-TUM** [comment]
Tip for programs where you can't change this yourself: If you'd create a symlink of the destination folder `output`, which `md-flex` uses, which points to `$SCRATCH` then this would be used.
So what I'm trying to say:
```bash
ln -s ${SCATCH}/whatever ~/your/AutoPas/buildDir/output
```

**Comment by FG-TUM** [comment]
fixed via #741
