### ISSUE TITLE
Don't throw if energy measurement is unavailable

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#773]
**Is your feature request related to a problem? Please describe.**
Currently, if energy measurements are not possible, an exception is thrown, caught, and then AutoPas continues. This is bad because we incorporate Exceptions in the logic flow. Also, it is annoying during debugging.

**Describe the solution you'd like**
No exception as long as the problem is not critical.

Instead of throwing, the respective functions could return a `std::string`, which is either empty on success or contains the error message that is currently in the exceptions.

**Describe alternatives you've considered**
?

**Additional context**
- Here, the returned strings could actually throw exceptions if necessary.
https://github.com/AutoPas/AutoPas/blob/8ae7ba5d754e124d5c8b81311eb81f1909e65509/src/autopas/selectors/AutoTuner.cpp#L43-L54
- Functions that throw exceptions are, for example:
  - https://github.com/AutoPas/AutoPas/blob/8ae7ba5d754e124d5c8b81311eb81f1909e65509/src/autopas/utils/RaplMeter.cpp#L44-L149
  - https://github.com/AutoPas/AutoPas/blob/8ae7ba5d754e124d5c8b81311eb81f1909e65509/src/autopas/utils/RaplMeter.cpp#L22-L42

**Comment by thesamriel** [comment]
**Adding on to that:**

In my opinion, energy measurements should be a feature that needs to be turned on explicitly.
The warning generated in L51 should, therefore, only be shown if the user actually requested information on energy.

https://github.com/AutoPas/AutoPas/blob/8ae7ba5d754e124d5c8b81311eb81f1909e65509/src/autopas/selectors/AutoTuner.cpp#L43-L54
