### ISSUE TITLE
Interoperability of Containers

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#80]
**Is your feature request related to a problem? Please describe.**
Particle Exchange (leaving and halo) of verlet lists + linked cells is complicated.

**Describe the solution you'd like**
Multiple MPI-Ranks with different Containers should be interoperable.

![img_20180731_120840](https://user-images.githubusercontent.com/38119442/43453789-423fd91a-94bb-11e8-951e-7aca6e82c377.jpg)

**Comment by FG-TUM** [comment]
Related: #172

**Comment by SteffenSeckler** [comment]
fixed #278
