### ISSUE TITLE
Safer Particle Movement

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#819]
**Is your feature request related to a problem? Please describe.**

One of the biggest assumptions that we make is that particles never move further than `skin / 2` during two rebuild steps. However, we have no good way to check this since particle movement is usually part of the user code.

**Describe the solution you'd like**
We control the interface to the particles via `Particlebase`. The only way to move a particle is to change its position (`r`) via `setR()`. Here we should add another method:
```cpp
// skinPerStepHalvedSquared = (skin / rebuildFreq / 2)^2
bool setRChecked(const std::array<double, 3> &r, double skinPerStepHalvedSquared)
```
This method should check whether the difference between the old and new positions is bigger than skin per step / 2 and return the result of that check.
Nevertheless, the method should still set the new `r` since the user is then free to choose what to do with this information (ignore / throw / ... ?).

**Describe alternatives you've considered**
1. Remove `setR()` to force the check always, but this seems unnecessarily harsh.
2. Instead of `ParticleBase::setRChecked()` add some utility function somewhere à la `isMovementTooFar(rOld, rNew, skinPerStepHalvedSquared)`. The disadvantage is that it involves more argument pushing.

**Additional context**
- Technically, this restriction is too strict since a particle can move back and forth or faster and slower, and we only get a problem if the total movement over the whole rebuild frequency is farther than `skin / 2`. However, this is the best approximation we can do and the user:
  - is not forced to use it.
  - can implement further checks if false is returned.
  - can give a wider skin to the check (not a good idea but possible)
- MD-flexible already does this, so we can simply move parts of the implementation from there into AutoPas.
- We should use this in ls1 and throw exceptions or at least warnings there.

**Comment by SamNewcome** [comment]
Another alternative is to completely switch over to dynamic rebuilding (e.g. in #789 ). In Luis Gall's [thesis](https://mediatum.ub.tum.de/node?id=1720413), he found this was always better than the current approach. As part of this, if I remember correctly, the position from the previous rebuild is stored and checked against skin size / 2 at every timestep (I can't remember which function). This would also solve the problem you describe.

The flaw of this approach is if you still want to use the current containers. I would suggest either 

- completely moving over to the dynamic approach (speak to @manishmishra6016  + we would need to implement a dynamically rebuilding version of Linked Cells). I am provisionally in favour of this anyway (but provisional on more testing)
- Implementing the approach as you describe, but allowing a way to avoid checked position sets dependent on the particle container.

**Comment by FG-TUM** [comment]
> the position from the previous rebuild is stored

Nope, that is only in MD-Flex. ls1 and any leap-frog-based simulation will not have that, which is why our `ParticleBase` also doesn't have it.

> allowing a way to avoid checked position sets dependent on the particle container

IMHO, this would significantly increase maintenance complexity :/
