### ISSUE TITLE
Add option to link against an external uuid build

### ISSUE THREAD

**Issue by SamNewcome** [AutoPas/AutoPas#864]
**Describe the bug**
You can't compile AutoPas on the ARM minicluster. This does not appear related to it being an ARM architecture but that it does not have much software. But it is important that we can compile on the minicluster because it has ARM CPUs.

The issue appears to stem from needing to make `uuid` (a dependency of ANTLR) as it is not on the system. When compiling `uuid`, `automake-1.13` is not found causing the compilation to break. The system has `automake-1.16`.

Bizarrely, `uuid` can be compiled manually.

**To Reproduce**
Compile AutoPas on the ARM minicluster using `gcc-11`:

I get:

```bash
[ 35%] Performing build step for 'uuid_bundled'
gmake[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
 cd . && /bin/sh /home/sam/AutoPas/build/uuid/src/uuid_bundled/missing automake-1.13 --foreign
/home/sam/AutoPas/build/uuid/src/uuid_bundled/missing: line 81: automake-1.13: command not found
WARNING: 'automake-1.13' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
gmake[4]: *** [Makefile:395: Makefile.in] Error 1
make[3]: *** [CMakeFiles/uuid_bundled.dir/build.make:86: uuid/src/uuid_bundled-stamp/uuid_bundled-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:542: CMakeFiles/uuid_bundled.dir/all] Error 2
```

~~Potentially this could be reproducible on another machine without `uuid`.~~

**Expected behavior**
The program compiles.

**Build environment (please complete the following information):**
* OS: Linux
* Compiler: GCC 11.2.1
* Build System: CMake 3.26.3

**Potential Solutions**

1. Recheck that there is nothing incorrect being done in `autopas_antlr4cpp`. Potentially a fresh set of eyes might spot something.
2. Add an option to link against an external `libuuid`.

**Comment by FG-TUM** [comment]
When uuid is installed (Ubuntu: `uuid-dev`) our CMake code picks it up and uses it.
