### ISSUE TITLE
More descriptive logging

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#87]
**Is your feature request related to a problem? Please describe.**
Currently, it is not always clear where log messages come from as they do not necessarily include file and function information.

**Describe the solution you'd like**
Using spdlog's macros like `SPDLOG_DEBUG(AutoPasLogger, ... )`

**Describe alternatives you've considered**
Strong self-discipline in cohesive log output formulation. (<- lol not happening).

**Comment by SteffenSeckler** [comment]
https://github.com/gabime/spdlog/blob/ba337d1393db312dedf41d7b2c4b608e7f4f8a90/include/spdlog/spdlog.h

https://github.com/gabime/spdlog/issues/235
