### ISSUE TITLE
'Trying to add a halo particle that is not outside the box of the container' crashes MPI runs

### ISSUE THREAD

**Issue by ManuelLerchner** [AutoPas/AutoPas#891]
**Describe the bug**

The bug described in #863 and seemingly fixed in #882 can still appear in MPI runs.

As far as I can tell `OMP_NUM_THREADS=14 mpiexec -n 4 ./md-flexible --yaml-filename SpinodalDecomposition.yaml` always crashes at ~200 iterations with:

```txt
Rank 3 : LogicHandler: Trying to add a halo particle that is not outside the box of the container.
Box Min [44.4528, 44.6316, -0.75]
Box Max [89.25, 89.25, 89.25]
MoleculeLJ
ID                 : 145460
Position           : [89.2469, 45.3053, 50.1878]
Velocity           : [-0.905947, 0.795215, -0.0735168]
Force              : [0, 0, 0]
Old Force          : [-7.36761, 3.50546, 8.89747]
Type ID            : 0
OwnershipState     : owned
```
The Full log file can be found here: [log.txt](https://github.com/user-attachments/files/15903357/log.txt)

**To Reproduce**
I would recommend testing it on CoolMuc as it takes ages locally.

1. Login on CoolMuc2
2. Setup the Scenario file (uploaded below), and copy the checkpoint files (also uploaded below) to the correct path.
3. Launch an interactive session using `salloc --ntasks=4 --partition=cm2_inter`
4. Execute: `OMP_NUM_THREADS=14 mpiexec -n 4 ./md-flexible --yaml-filename SpinodalDecomposition.yaml`
5. Wait for crash at ~200 iterations (Sometimes it also crashes at ~400 iterations. It isn't deterministic :/ )

**Screenshots**

The checkpoint file describes a scaled down Spinodal decomposition with `60x60x60` particles at `1.5 spacing`

![image](https://github.com/AutoPas/AutoPas/assets/54124311/723bb9bc-1160-41ad-9df6-8f7a1ad3a0eb)

**Build environment (please complete the following information):**
* Compiled on CoolMuc2 with
* `gcc/11` and `cmake/3.21.4`;

**Additional context**

Here are all the files needed to reproduce this error:

[SpinodalDecomposition.yaml](https://github.com/user-attachments/files/15903385/SpinodalDecomposition.txt)

[SpinodalDecomposition_equilibration.zip](https://github.com/user-attachments/files/15903540/SpinodalDecomposition_equilibration.zip)

**Comment by SamNewcome** [comment]
This appears related to the load balancer - don't have specifics yet but crashes occur exactly when the load is balanced (tested with intervals 50, 183, 200 - 183 is obscure enough that I think this can't be a coincidence). With load balancer set to none I was able to run 1000 iterations (at which point the simulation ended - not crashed).

I am unsure how much time I will have to fix the issue over the next week, but for now don't use the load balancer.
