### ISSUE TITLE
explodingLiquid fails on branch Dynamic-VL-merge

### ISSUE THREAD

**Issue by MehdiHachicha** [AutoPas/AutoPas#892]
**Describe the bug**
MD-Flexible's explodingLiquid input performs a few iterations, then fails with the following (summarized) message:
AutoPasException: LogicHandler: Trying to add a halo particle that is not outside the box of the container. Box Min [-0.5, 0, -0.5], Box Max [15.5, 60, 15.5].

**To Reproduce**
1. git clone https://github.com/AutoPas/AutoPas.git
2. cd AutoPas && git checkout Dynamic-VL-merge
3. mkdir build-dvl && cd build-dvl
4. cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DMD_FLEXIBLE_USE_MPI=OFF ..
5. make -j4 md-flexible
6. cd examples/md-flexible && ./md-flexible --yaml-filename explodingLiquid.yaml

Error at iteration 89/12000:
terminate called after throwing an instance of 'autopas::utils::ExceptionHandler::AutoPasException'
terminate called recursively
Aborted (core dumped)

**Expected behavior**
On the master branch, the simulation finishes as expected (but with warnings).

**Build environment (please complete the following information):**
* OS: Ubuntu, also CoolMUC-2
* Compiler: clang
* Build System: Make

**Comment by FG-TUM** [comment]
possibly duplicate of #891

**Comment by manishmishra6016** [comment]
I think this is fixed now. Somehow changes from bug fix in #882 was ignored while merging master into this branch. This is still without MPI, so not sure it fixes the problem in #891
