### ISSUE TITLE
Non-Tuning-Phase length behavior

### ISSUE THREAD

**Issue by FG-TUM** [AutoPas/AutoPas#942]
**Is your feature request related to a problem? Please describe.**
Currently, the number of iterations between two tuning phases, which we call the tuning frequency, is a fixed number of iterations. These iterations are counted after the last tuning iteration.
This means that when a tuning strategy is employed where the number of tuning iterations is not known in advance, it is hard to estimate when the next tuning phase will start.

**Describe the solution you'd like**
The number of tuning iterations is subtracted from the non-tuning iterations. Meaning if we specify a tuning frequency of e.g. 1000 tuning will always start at iteration 0, 1000, 2000, ...

**Describe alternatives you've considered**
- [ ] ~Option A: Leave everything as it is. (meh)~
- [x] Option B: Implement the suggested behavior.
- [ ] ~Option C: Implement the suggested behavior without replacing the old one and provide an option to switch between the two.~

**Additional context**
This behavior would help to synchronize tuning and MPI load balancing.

**Comment by SamNewcome** [comment]
I like B
